version: '3'
services:
 nginx:
  container_name: nginx
  image: nginx:1.16
  network_mode: "host"
  ports:
   - "80:80"
  volumes:
   - ./nginx/conf.d:/ect/nginx/conf.d
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
 
 php:
  container_name: php
  image: php7.1:latest
  restart: always
  ports:
   - "8080:80"
  volumes:
   - /home/justin/pubic_html:/var/www/html
   - ./apache2/apache2.conf:/etc/apache2/apache2.conf
   - ./apache2/ports.conf:/etc/apache2/ports.conf
   - ./apache2/http-vhosts.conf:/etc/apache2/http-vhosts.conf
   - ./php/php.ini:/usr/local/etc/php/php.ini
  networks:
   lampp_net:
    ipv4_address: 10.5.0.4
 
 mysql:
  container_name: mysql
  image: mysql:5.7
  restart: always
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: root
  volumes:
   - ./mysql/data:/var/lib/mysql
  networks:
   lampp_net:
    ipv4_address: 10.5.0.6
  

networks:
 lampp_net:
  driver: bridge
  ipam:
   config:
    - subnet: 10.5.0.0/16
  
